version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VENV_PATH=/venv
      - PATH=/venv/bin:$PATH
    ports:
      - 8501:8501
    volumes:
      - .:/app
    command: tgcf-web
